"""Update company

Revision ID: 6c63bfbe4ef5
Revises: 
Create Date: 2024-02-21 15:00:45.298343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c63bfbe4ef5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sports_club')
    op.drop_table('user')
    op.add_column('company', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'website')
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.create_table('sports_club',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sports_participated', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contactinfo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('membershipyears2000and2022and2023', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('feespaid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sports_club_pkey')
    )
    # ### end Alembic commands ###
